// app/layout.tsx

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./styles/globals.css"; // Import your global CSS (corrected path)
import "stream-chat-react/dist/css/v2/index.css"; // Import Stream Chat CSS
// Note: Adjust the import path based on the version of stream-chat-react you're using

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
